### ISSUE TITLE
`element_interface` not in requirements

### ISSUE THREAD

**Issue by sneakers-the-rat** [datajoint/element-array-ephys#66]
`element_interface` is imported from:
https://github.com/datajoint/element-array-ephys/blob/14517a27288cf2a2ddfd526da64a2d32da69b156/element_array_ephys/ephys_chronic.py#L7

but it's not in the requirements:
https://github.com/datajoint/element-array-ephys/blob/main/requirements.txt

so the module can't be imported.

**Comment by kabilar** [comment]
Thanks for the report @sneakers-the-rat.  We opted not to keep [element-interface](https://github.com/datajoint/element-interface) in the `requirements.txt` because `element-interface` is used to install third-party packages, some of which are not on PyPI.  From what I understand, all packages within the `requirements.txt` or `setup.py` must be published to PyPI in order for the package of interest to be published to PyPI.  Please let us know if you have any suggestions as we are trying to find a cleaner way of setting up these dependencies.

**Comment by sneakers-the-rat** [comment]
you can require something from git in a requirements.txt file! 

```
package-name @ git+https://github.com/whatever/repo@branchname
```

see https://pip.pypa.io/en/stable/topics/vcs-support/

I have several packages on PyPI that have git dependencies, so it's definitely allowed! for example: https://github.com/wehr-lab/autopilot/blob/637064da3d10e9eeb186483827c8b7dadaa2f356/pyproject.toml#L55
